# Generated by Django 2.1.5 on 2019-01-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoEclesiastico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Obrigatório. 45 caracteres ou menos.', max_length=45, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Congregacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('setor', models.IntegerField(verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Congregação',
                'verbose_name_plural': 'Congregações',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.BigIntegerField(unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=5, verbose_name='Sexo')),
                ('identidade', models.BigIntegerField(verbose_name='Identidade')),
                ('orgao_emissor', models.CharField(max_length=6, verbose_name='Orgão emissor')),
                ('telefone', models.BigIntegerField(verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.CargoEclesiastico')),
                ('congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.Congregacao')),
            ],
        ),
    ]
