# Generated by Django 2.1.5 on 2019-01-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_auto_20190114_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('V', 'Viúvo')], default='S', max_length=5, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='orgao_emissor',
            field=models.CharField(max_length=6, verbose_name='Orgão Emissor'),
        ),
    ]
