# Generated by Django 2.1.5 on 2019-01-16 16:58

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_auto_20190114_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.BigIntegerField(verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', localflavor.br.models.BRStateField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cargoeclesiastico',
            options={'verbose_name': 'Cargo Eclesiástico', 'verbose_name_plural': 'Cargos Eclesiásticos'},
        ),
        migrations.RemoveField(
            model_name='membro',
            name='Cep',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='estado',
        ),
        migrations.AlterField(
            model_name='membro',
            name='conjuge',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cônjuge'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.Membro'),
        ),
    ]
