# Generated by Django 2.1.5 on 2019-01-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_auto_20190116_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_batismo', models.DateField(verbose_name='Data de batismo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.Membro')),
            ],
            options={
                'verbose_name': 'Historico',
            },
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
