# Generated by Django 2.1.5 on 2019-01-21 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_auto_20190116_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Histórico'},
        ),
        migrations.AddField(
            model_name='membro',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2019, 1, 21), verbose_name='Data de cadastro'),
        ),
    ]
