# Generated by Django 2.1.5 on 2019-02-16 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_auto_20190121_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='nacionalidade',
            field=models.CharField(default='Brasileiro(a)', max_length=15, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='membro',
            name='naturalidade',
            field=models.CharField(default='Rio de Janeiro', max_length=15, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='membro',
            name='profissao',
            field=models.CharField(default='Estudante', max_length=15, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='membro',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2019, 2, 16), verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viúvo(a)'), ('D', 'Divorciado(a)')], default='S', max_length=5, verbose_name='Estado Civil'),
        ),
    ]
