# Generated by Django 2.1.5 on 2019-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_auto_20190216_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='data_cadastro',
            field=models.CharField(default='16/2/2019', max_length=10, verbose_name='Data de Cadastro'),
        ),
    ]
