# Generated by Django 2.1.5 on 2019-07-26 13:27

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_auto_20190216_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['matricula', 'cargo']},
        ),
        migrations.AddField(
            model_name='membro',
            name='bairro',
            field=models.CharField(default='Tijuca', max_length=30, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='membro',
            name='cep',
            field=models.BigIntegerField(default=20080, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='cidade',
            field=models.CharField(default='Rio de Janeiro', max_length=30, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='membro',
            name='complemento',
            field=models.CharField(default='Apartamento', max_length=50, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='descricao',
            field=models.CharField(default='Rua', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='estado',
            field=localflavor.br.models.BRStateField(default='RJ', max_length=2),
        ),
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(default='genome.png', upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_cadastro',
            field=models.CharField(default='26/7/2019', max_length=10, verbose_name='Data de Cadastro'),
        ),
    ]
