# Generated by Django 2.1.5 on 2019-09-14 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_auto_20190729_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacao',
            name='setor',
            field=models.CharField(max_length=2, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2019, 9, 14), max_length=10, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='recebimento',
            field=models.CharField(choices=[('A', ' Por aclamação'), ('M', 'Com carta de mudança'), ('B', 'Por Batismo nas Águas'), ('C', 'Por Convenção')], default='B', max_length=5, verbose_name='Recebimento'),
        ),
    ]
